### ISSUE TITLE
请问下，执行中遇到该问题怎么解决？

### ISSUE THREAD

**Issue by zhanghaobucunzai** [xiaomengyc/SPG#16]
=> loaded checkpoint '/user/pytorch/SPG-master/vgg16-397923af.pth'
Max iter: 320295
Traceback (most recent call last):
  File "train_frame.py", line 194, in <module>
    train(args)
  File "train_frame.py", line 120, in train
    res = my_optim.reduce_lr(args, optimizer, current_epoch)
  File "/user/pytorch/SPG-master/exper/my_optim.py", line 75, in reduce_lr
    if change_points is not None and epoch in change_points:
  File "/user/pytorch/SPG-master/exper/my_optim.py", line 71, in <lambda>
    change_points = map(lambda x: int(x.strip()), values)
ValueError: invalid literal for int() with base 10: 'none'

**Comment by zhanghaobucunzai** [comment]
已经解决  需要将python2代码转换成python3
