### ISSUE TITLE
pre trained model of CUB?

### ISSUE THREAD

**Issue by FzuLJ** [xiaomengyc/SPG#4]
Can you please provide a pre trained model for CUB-200-2011?

**Comment by xiaomengyc** [comment]
@FzuLJ   
Sorry for the late reply. The trained model on CUB dataset has been uploaded at https://drive.google.com/open?id=1WfrELBlEoq5WO7gKUv-MLTQ8QHY-2wiX

**Comment by Rahul-Venugopal** [comment]
Thanks for sharing the trained model.  I am not able to extract the model.

I downloaded the file from [https://drive.google.com/file/d/1WfrELBlEoq5WO7gKUv-MLTQ8QHY-2wiX/view][1] and it got downloaded as **file_name.zip**. 

Then I extracted the file using **extract here** option by right click . 
Now a new file in format .tar i.e **filename.tar** is created in the same directory.

When I try to extract filename.tar from terminal using the command 

    tar -xvf filename.tar
I get the error :

    tar: This does not look like a tar archive
    tar: Skipping to next header
    tar: Exiting with failure status due to previous errors

when I check the file type using command :
   

    file filename.tar

I get the result as :
  

    filename.tar : 8086 relocatable (Microsoft)

Can anyone help me to understand what I am doing wrong ?

  [1]: https://drive.google.com/file/d/1WfrELBlEoq5WO7gKUv-MLTQ8QHY-2wiX/view

**Comment by Rahul-Venugopal** [comment]
When I run `sh val_cub_full.sh` , 
I am getting following **output** / Error

Project Root Dir: /home/rahul/Desktop/Thesis/Reference/WSOL/ACoL/SPG
Running parameters:

{
    "root_dir":"/home/rahul/Desktop/Thesis/Reference/WSOL/ACoL/SPG",
    "train_list":"/home/rahul/Desktop/Thesis/Reference/WSOL/ACoL/SPG/datalist/CUB/train_list.txt",
    "tencrop":"False",
    "threshold":0.5,
    "onehot":"True",
    "restore_from":"",
    "test_list":"/home/rahul/Desktop/Thesis/Reference/WSOL/ACoL/SPG/datalist/CUB/test_list.txt",
    "num_gpu":1,
    "crop_size":321,
    "disp_interval":20,
    "resume":"True",
    "snapshot_dir":"../snapshots/inception_imagenet_full_spg/",
    "epoch":21,
    "lr":0.001,
    "input_size":356,
    "current_epoch":0,
    "num_workers":20,
    "batch_size":1,
    "global_counter":0,
    "dataset":"cub",
    "arch":"inception3_spg",
    "num_classes":200,
    "img_dir":"/home/rahul/Desktop/Thesis/Reference/WSOL/ACoL/SPG/data/CUB_200_2011/images",
    "decay_points":"none"
}
```
../models/google/inception3_spg.py:137: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight.data)
=> no checkpoint found at ''
0it [00:00, ?it/s]/home/rahul/.virtualenvs/acol/local/lib/python2.7/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/home/rahul/.virtualenvs/acol/local/lib/python2.7/site-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))

Traceback (most recent call last):
  File "val_frame.py", line 203, in <module>
    val(args)
  File "val_frame.py", line 132, in val
    val_mAP, prob, gt = cal_mAP(logits0, label_var, prob, gt)
  File "val_frame.py", line 178, in cal_mAP
    assert logits0.size() == label_var.size()
AssertionError
```

Any suggestions about the mistake I am making ?

**Comment by xiaomengyc** [comment]
@Rahul-Venugopal 
You got to change to  `onehot=False` if your images do not have multiclasses.
